version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: shop_api
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - shop_api
        depends_on:
            - db
        ports:
            - "9000:9000"

    nginx:
        image: nginx:1.25
        container_name: nginx
        restart: unless-stopped
        volumes:
            - .:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"
        networks:
            - shop_api
        depends_on:
            - app

    db:
        image: mysql
        container_name: mysql # name should be same with the DB_HOST in the .env file
        volumes:
            - ./mysql/data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USERNAME: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}

volumes:
    mysql_data:

networks:
    shop_api:
